apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  namespace: jellyfin
  labels:
    app: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      containers:

        # Jellyfin server
        - name: jellyfin
          image: jellyfin/jellyfin:latest
          ports:
            - containerPort: 8096
          volumeMounts:
            - name: jellyfin-media
              mountPath: /media
            - name: config
              mountPath: /config

      volumes:
        - name: jellyfin-media
          persistentVolumeClaim:
            claimName: jellyfin-media-pvc
        - name: config
          persistentVolumeClaim:
            claimName: jellyfin-config-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin-service
  namespace: jellyfin
spec:
  type: LoadBalancer
  ports:
    - port: 8096
      targetPort: 8096
  selector:
    app: jellyfin
