apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-media-pv
spec:
  capacity:
    storage: 400Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: rclone.csi.k8s.io
    volumeHandle: jellyfin-media-volume
    readOnly: false
    volumeAttributes:
      remote: minio:jellyfin-media
      configSecretName: rclone-config-secret
