namespace: nfs-storage 

nfs:
  server: 192.168.20.100
  path: /srv/nfs

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - pi-master

