apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv-pi-master
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path 
  local:
    path: /var/lib/rancher/k3s/storage/minio/pi-master
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - pi-master

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv-pi-1
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path 
  local:
    path: /var/lib/rancher/k3s/storage/minio/pi-1
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - pi-1

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv-pi-2
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path 
  local:
    path: /var/lib/rancher/k3s/storage/minio/pi-2
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - pi-2

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv-pi-3
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path 
  local:
    path: /var/lib/rancher/k3s/storage/minio/pi-3
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - pi-3

